-- Create UserSessions table
CREATE TABLE IF NOT EXISTS `UserSessions` (
    `Id` CHAR(36) NOT NULL,
    `UserId` CHAR(36) NOT NULL,
    `SessionToken` VARCHAR(500) NOT NULL,
    `IpAddress` VARCHAR(45) NULL,
    `UserAgent` VARCHAR(500) NULL,
    `LoginAt` DATETIME(6) NOT NULL,
    `LogoutAt` DATETIME(6) NULL,
    `ExpiresAt` DATETIME(6) NOT NULL,
    `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
    `CreatedAt` DATETIME(6) NOT NULL,
    `UpdatedAt` DATETIME(6) NULL,
    `CreatedBy` CHAR(36) NULL,
    `UpdatedBy` CHAR(36) NULL,
    `IsDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `DeletedAt` DATETIME(6) NULL,
    `DeletedBy` CHAR(36) NULL,
    PRIMARY KEY (`Id`),
    UNIQUE KEY `IX_UserSessions_SessionToken` (`SessionToken`),
    KEY `IX_UserSessions_UserId` (`UserId`),
    KEY `IX_UserSessions_IsActive` (`IsActive`),
    KEY `IX_UserSessions_ExpiresAt` (`ExpiresAt`),
    CONSTRAINT `FK_UserSessions_Usuarios_UserId` FOREIGN KEY (`UserId`) REFERENCES `Usuarios` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;