// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sis.Pdv.Blazor.Data;

#nullable disable

namespace Sis.Pdv.Blazor.Data.Migrations
{
    [DbContext(typeof(PdvDbContext))]
    partial class PdvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sis.Pdv.Blazor.Data.Entities.ItemVendaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Cancelado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Sequencial")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("IX_ItensVenda_VendaId");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("Sis.Pdv.Blazor.Data.Entities.ProdutoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CodBarras")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoqueProduto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodBarras")
                        .IsUnique()
                        .HasDatabaseName("IX_Produtos_CodBarras");

                    b.HasIndex("NomeProduto")
                        .HasDatabaseName("IX_Produtos_Nome");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Sis.Pdv.Blazor.Data.Entities.VendaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Cancelada")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CpfCnpjCliente")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NomeOperador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Sincronizada")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Troco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataVenda")
                        .HasDatabaseName("IX_Vendas_DataVenda");

                    b.HasIndex("Sincronizada")
                        .HasDatabaseName("IX_Vendas_Sincronizada");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Sis.Pdv.Blazor.Data.Entities.ItemVendaEntity", b =>
                {
                    b.HasOne("Sis.Pdv.Blazor.Data.Entities.VendaEntity", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Sis.Pdv.Blazor.Data.Entities.VendaEntity", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Sis.Pdv.Blazor.Data.Entities.VendaRascunhoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NomeOperador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CpfCnpjCliente")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItensJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCaixa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("VendasRascunho");
                });
#pragma warning restore 612, 618
        }
    }
}
